version: '3'
services:
  wp:
    depends_on: [mysql]
    build: .
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_PASSWORD: qwerty
    volumes:
      - ./wordpress:/var/www/html
      
  mysql:
    
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
    volumes:
      - database-wp-dev:/var/lib/mysql
volumes:
  database-wp-dev:
